# Generated by : https://gemini.google.com/share/41b597335892

import os
import json
import ctypes
import hashlib
from pathlib import Path
from typing import List, Dict, Optional, Any

from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives import hashes

# Re-importing our models for a fully self-contained script
from pydantic import BaseModel, Field

# ==========================================
# 0. MEMORY SECURITY UTILITIES
# ==========================================

def burn_string(s: Optional[str]):
    """
    Overwrites the underlying memory buffer of a Python string with 
    cryptographically secure random bytes to defeat resident memory attacks 
    and disguise memory clearing patterns.
    """
    if not s:
        return
        
    # Determine Python internal string memory offset dynamically
    import sys
    sys_string_offset = sys.getsizeof("") - 1
    
    # Get the memory address of the string buffer and its length
    location = id(s) + sys_string_offset
    size = len(s)
    
    if size > 0:
        # Generate cryptographically secure random bytes matching the string size
        random_noise = os.urandom(size)
        
        # Get a raw pointer to the random bytes buffer
        noise_buffer = ctypes.c_char_p(random_noise)
        
        # Overwrite the original string's location with the random noise buffer
        ctypes.memmove(location, noise_buffer, size)
        
# Determine Python internal string memory offset dynamically
import sys
sys_string_offset = sys.getsizeof("") - 1


# ==========================================
# 1. DATA MODELS
# ==========================================

class EncryptedContainer(BaseModel):
    ciphertext: str
    iv: str
    salt: str
    hint_description: str


class SecretModel(BaseModel):
    service_name: str
    user: str
    encrypted_data: EncryptedContainer

    @property
    def secure_filename(self) -> str:
        normalized_user = self.user.strip().lower()
        normalized_service = self.service_name.strip().lower()
        combined_string = f"{normalized_user}||{normalized_service}"
        hash_digest = hashlib.sha256(combined_string.encode('utf-8')).hexdigest()
        return f"{hash_digest}.json"


class DecryptedSecretPayload(BaseModel):
    url_or_app: str
    category: str = "General"
    payload: Dict[str, Any]
    hint_value: str


# ==========================================
# 2. SECRETS MANAGER
# ==========================================

class FamilySecretsManager:
    def __init__(self, storage_dir: str = None):
        if storage_dir is None:
            # Attempt to load from config file
            config_path = Path(__file__).parent / "config.yml"
            if config_path.exists():
                with open(config_path, "r") as f:
                    import yaml
                    config = yaml.safe_load(f)
                    storage_dir = config.get("vault_path", "./family_vault")
            else:
                storage_dir = "./family_vault"

        self.storage_dir = Path(storage_dir)
        self.storage_dir.mkdir(exist_ok=True)

    def _derive_key(self, master_key: str, hint_value: str, salt: bytes) -> bytes:
        """Derives a strong 256-bit AES key using PBKDF2 from Master Key + Hint Value."""
        # Combine master key and dynamic hint value to create the base key material
        combined_key_material = f"{master_key}||{hint_value}".encode('utf-8')
        
        kdf = PBKDF2HMAC(
            algorithm=hashes.SHA256(),
            length=32,
            salt=salt,
            iterations=100_000
        )
        return kdf.derive(combined_key_material)

    def save_secret(self, user: str, service_name: str, master_key: str, decrypted_payload: DecryptedSecretPayload, hint_description: str):
        """Encrypts a generic payload and saves it to its own obfuscated file."""
        salt = os.urandom(16)
        iv = os.urandom(12)
        
        # Derive encryption key
        key = self._derive_key(master_key, decrypted_payload.hint_value, salt)
        
        # Serialize payload to plain JSON text
        plain_text_json = decrypted_payload.model_dump_json()
        
        # Encrypt via AES-GCM
        aesgcm = AESGCM(key)
        ciphertext_bytes = aesgcm.encrypt(iv, plain_text_json.encode('utf-8'), None)
        
        # Package into the secure layout
        container = EncryptedContainer(
            ciphertext=ciphertext_bytes.hex(),
            iv=iv.hex(),
            salt=salt.hex(),
            hint_description=hint_description
        )
        
        secret_file_model = SecretModel(
            service_name=service_name,
            user=user,
            encrypted_data=container
        )
        
        # Save to disk using the secure hash name
        file_path = self.storage_dir / secret_file_model.secure_filename
        with open(file_path, "w") as f:
            f.write(secret_file_model.model_dump_json(indent=4))
            
        print(f"[Success] Saved encrypted record to isolated file: {secret_file_model.secure_filename}")

    # ----------------------------------------------------
    # REQUIREMENT 1: DYNAMIC MENU (Filtered by individual User)
    # ----------------------------------------------------
    def get_dynamic_menu(self, target_user: str) -> List[Dict[str, str]]:
        """
        Scans the directory and constructs a dynamic user menu.
        Only displays services that belong to the queried family member.
        """
        menu = []
        normalized_target = target_user.strip().lower()

        for file_path in self.storage_dir.glob("*.json"):
            try:
                with open(file_path, "r") as f:
                    data = json.load(f)
                    # Safely load metadata parameters without decrypting the payload
                    envelope = SecretModel(**data)
                    
                    if envelope.user.strip().lower() == normalized_target:
                        menu.append({
                            "service_name": envelope.service_name,
                            "hint_clue": envelope.encrypted_data.hint_description
                        })
            except Exception:
                # Ignore corrupt or non-manager files in vault directory
                continue
        return menu

    # ----------------------------------------------------
    # REQUIREMENT 2: DECRYPT WITH IMMEDIATE MEMORY SCRUBBING
    # ----------------------------------------------------
    def decrypt_secret(self, user: str, service_name: str, master_key: str, hint_value: str) -> Optional[Dict[str, Any]]:
        """
        Locates the specific secret file, decrypts it, prints/returns the data, 
        and systematically shreds plain text remnants from RAM.
        """
        # Form a mock envelope to effortlessly calculate the secure target filename
        mock_envelope = SecretModel(
            service_name=service_name,
            user=user,
            encrypted_data=EncryptedContainer(ciphertext="", iv="", salt="", hint_description="")
        )
        
        file_path = self.storage_dir / mock_envelope.secure_filename
        if not file_path.exists():
            print("[-] Error: No matching record found for that User/Service combination.")
            return None

        # Load file
        with open(file_path, "r") as f:
            envelope = SecretModel(**json.load(f))
            
        container = envelope.encrypted_data
        
        # Convert hex strings back to operational byte format
        salt = bytes.fromhex(container.salt)
        iv = bytes.fromhex(container.iv)
        ciphertext = bytes.fromhex(container.ciphertext)
        
        # Core operational block
        plain_json_str = None
        try:
            # Reconstruct the dynamic evaluation key
            key = self._derive_key(master_key, hint_value, salt)
            aesgcm = AESGCM(key)
            
            # Decrypt payload back to clean JSON string
            decrypted_bytes = aesgcm.decrypt(iv, ciphertext, None)
            plain_json_str = decrypted_bytes.decode('utf-8')
            
            # Rehydrate string into structured Pydantic format for memory validation
            decrypted_model = DecryptedSecretPayload.model_validate_json(plain_json_str)
            
            # Extract credentials payload dictionary to return to terminal/UI layer
            exposed_credentials = decrypted_model.payload.copy()
            
            return exposed_credentials
            
        except Exception:
            print("[-] Cryptographic Failure: Invalid Master Key or Incorrect Hint Value.")
            return None
            
        finally:
            # Immediate Critical Memory Defense: Wipe plain text strings out of RAM
            if plain_json_str:
                burn_string(plain_json_str)
                del plain_json_str
    
    def delete_secret(self, user: str, service_name: str) -> bool:
        """Calculates the target obfuscated file and removes it if it exists."""
        mock_envelope = SecretModel(
            service_name=service_name,
            user=user,
            encrypted_data=EncryptedContainer(ciphertext="", iv="", salt="", hint_description="")
        )
        file_path = self.storage_dir / mock_envelope.secure_filename
        if file_path.exists():
            file_path.unlink()  # Deletes the file
            print(f"[Deleted] Removed isolated asset: {mock_envelope.secure_filename}")
            return True
        return False